language: python
python:
- 2.7
- 3.3
- 3.4
install:
- pip install coverage coveralls .
after_success:
- coveralls
script:
- coverage run setup.py test -a "--doctest-modules --pep8 -v tests/ RandomIO/"
- coverage report -m --include=RandomIO/*,bin/*
notifications:
  slack: storjcommunity:G9Q7PFrK7LQGTuomtP8h5oOH
